# Generated by Django 5.2.6 on 2025-12-05 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.DateField(default=django.utils.timezone.now)),
                ('total_ea_nsp', models.PositiveIntegerField()),
                ('total_ea_notivisa', models.PositiveIntegerField()),
                ('total_pulseiras', models.PositiveIntegerField()),
                ('total_ea_queda', models.PositiveIntegerField()),
                ('total_ea_flebite', models.PositiveIntegerField()),
                ('taxa_conformidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_pacientes', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
